INSERT INTO movie_finder.film_country (`country_id`, `film_id`) VALUES 
('PE', '1'),
('UK','2'),
('GM','2'),
('US','2'),
('FR','2'),
('US','3'),
('US','4'),
('US','5'),
('FR','5'),
('UK','5'),
('GM','5'),
('ZA','5'),
('CA','5'),
('JA','5'),
('AU','5'),
('US','6'),
('US','7'),
('UK','7');