INSERT INTO movie_finder.person (`person_id`, `first_name`, `last_name`) VALUES
(1, 'Carlos', 'Alcantara'),
(2, 'Vanessa', 'Saba'),
(3, 'Marco', 'Zunino'),
(4, 'Johanna', 'San Miguel'),
(5, 'Wendy', 'Ramos'),
(6, 'Paul', 'Vega'),
(7, 'Erika', 'Villalobos'),
(8, 'Bruno', 'Ascenzo'),
(9, 'Julian', 'Gil'),
(10, 'Ryan', 'McCluskey'),
(11, 'Oscar', 'Pearce'),
(12, 'Indra', 'Ove'),
(13, 'Anna', 'Bolt'),
(14, 'Joseph', 'May'),
(15, 'Robert', 'Tannion'),
(16, 'Heike', 'Makatsch'),
(17, 'Jaymes', 'Butler'),
(18, 'Stephen', 'Billington'),
(19, 'Fiona', 'Glascott'),
(20, 'Milla', 'Jovovich'),
(21, 'Eric', 'Mabius'),
(22, 'Colin', 'Salmon'),
(23, 'Martin', 'Crewes'),
(24, 'Pasquale', 'Aleardi'),
(25, 'Michelle', 'Rodriguez'),
(26, 'Liz', 'Brice'),
(27, 'Torsten', 'Jerabek'),
(28, 'Marc', 'Logan-Black'),
(29, 'James', 'Purefoy'),
(30, 'Michaela', 'Dicker'),
(31, 'Barry', 'Best'),
(32, 'Jeremy', 'Bolt'),
(33, 'Jamie', 'Harding'),
(34, 'Jason', 'Isaacs'),
(35, 'Pharaoh', 'Lambert'),
(36, 'Michael', 'Sercerchi'),
(37, 'Giovanna', 'Spuria'),
(38, 'Denzel', 'Washington'),
(39, 'Ray', 'Allen'),
(40, 'Rosario', 'Dawson'),
(41, 'Hill', 'Harper'),
(42, 'Zelda', 'Harris'),
(43, 'Ned', 'Beatty'),
(44, '', 'Brown'),
(45, '', 'Taylor'),
(46, 'Bill', 'Nunn'),
(47, 'Michele', 'Shay'),
(48, 'Thomas', 'Byrd'),
(49, 'Roger', 'Smith'),
(50, 'John', 'Turturro'),
(51, 'Lonette', 'McKee'),
(52, '', 'Hill'),
(53, '', 'Parker'),
(54, '', 'Hallahan'),
(55, '', 'DeLong'),
(56, 'Iain', 'Glen'),
(57, 'Ali', 'Larter'),
(58, 'Shawn', 'Roberts'),
(59, 'Eoin', 'Macken'),
(60, 'Fraser', 'James'),
(61, 'Ruby', 'Rose'),
(62, 'William', 'Levy'),
(63, 'Rola', 'rola'),
(64, 'Ever', 'Anderson'),
(65, 'Mark', 'Simpson'),
(66, 'Milton', 'Schorr'),
(67, 'Siobhan', 'Hodgson'),
(68, 'Joon-Gi', 'Lee'),
(69, 'Aubrey', 'Shelton'),
(70, 'Ryan', 'Reynolds'),
(71, 'Josh', 'Brolin'),
(72, 'Morena', 'Baccarin'),
(73, 'Julian', 'Dennison'),
(74, 'Zazie', 'Beetz'),
(75, 'T.J.', 'Miller'),
(76, 'Leslie', 'Uggams'),
(77, 'Karan', 'Soni'),
(78, 'Brianna', 'Hildebrand'),
(79, 'Jack', 'Kesy'),
(80, 'Eddie', 'Marsan'),
(81, 'Shioli', 'Kutsuna'),
(82, 'Stefan', 'Kapicic'),
(83, 'Randal', 'Reeder'),
(84, 'Nikolai', 'Witschl'),
(85, 'Kevin', 'Costner'),
(86, 'Gary', 'Oldman'),
(87, 'Tommy', 'Lee'),
(88, 'Jordi', 'Molla'),
(89, 'Gal', 'Gadot'),
(90, 'Michael', 'Pitt'),
(91, 'Amaury', 'Nolasco'),
(92, 'Alice', 'Eve'),
(93, 'Antje', 'Traue'),
(94, 'Scott', 'Adkins'),
(95, 'Lara', 'Decaro'),
(96, 'Freddy', 'Bosche'),
(97, 'Emmanuel', 'Imani'),
(98, 'Harry', 'Hepple'),
(99,'Kevin','Spacey'),
(100,'Annette','Bening'),
(101,'Thora','Birch'),
(102,'Wes','Bentley'),
(103,'Mena','Suvari'),
(104,'Peter','Gallagher'),
(105,'Allison','Janney'),
(106,'Chris','Cooper'),
(107,'Scott','Bakula'),
(108,'Sam','Robards'),
(109,'Barry','Del Sherman'),
(110,'Ara','Celi'),
(111,'John','Cho'),
(112,'Fort','Atkinson'),
(113,'Sue','Casey'),
(114,'Woody', 'Allen'),
(115,'Diane','Keaton'),
(116,'Tony','Roberts'),
(117,'Carol','Kane'),
(118,'Paul', 'Simon'),
(119,'Shelley','Duvall'),
(120,'Janet','Margolin'),
(121,'colleen','dewhurst'),
(122,'Christopher','Walken'),
(123,'Donald','Symington'),
(124,'Helen','Ludlam'),
(125,'Mordecai','Lawner'),
(126,'Joan','Neuman'),
(127,'Jonathan','Munk'),
(128,'Ruth','Volner'),
(129,'Frank ', 'Pérez'),
(130,'Paul W.S.','Anderson'),
(131,'Spike','Lee'),
(132,'Danya','Taymor'),
(133,'David','leitch'),
(134,'Ariel','Vromen'),
(135,'Sam','Mendes');