INSERT INTO movie_finder.language VALUES ('ar', 'árabe');
INSERT INTO movie_finder.language VALUES ('ar_AE', 'árabe [Emiratos Árabes Unidos]');
INSERT INTO movie_finder.language VALUES ('ar_BH', 'árabe [Bahráin]');
INSERT INTO movie_finder.language VALUES ('ar_DZ', 'árabe [Argelia]');
INSERT INTO movie_finder.language VALUES ('ar_EG', 'árabe [Egipto]');
INSERT INTO movie_finder.language VALUES ('ar_IQ', 'árabe [Iraq]');
INSERT INTO movie_finder.language VALUES ('ar_JO', 'árabe [Jordania]');
INSERT INTO movie_finder.language VALUES ('ar_KW', 'árabe [Kuwait]');
INSERT INTO movie_finder.language VALUES ('ar_LB', 'árabe [Líbano]');
INSERT INTO movie_finder.language VALUES ('ar_LY', 'árabe [Libia]');
INSERT INTO movie_finder.language VALUES ('ar_MA', 'árabe [Marruecos]');
INSERT INTO movie_finder.language VALUES ('ar_OM', 'árabe [Omán]');
INSERT INTO movie_finder.language VALUES ('ar_QA', 'árabe [Qatar]');
INSERT INTO movie_finder.language VALUES ('ar_SA', 'árabe [Arabia Saudita]');
INSERT INTO movie_finder.language VALUES ('ar_SD', 'árabe [Sudán]');
INSERT INTO movie_finder.language VALUES ('ar_SY', 'árabe [Siria]');
INSERT INTO movie_finder.language VALUES ('ar_TN', 'árabe [Túnez]');
INSERT INTO movie_finder.language VALUES ('ar_YE', 'árabe [Yemen]');
INSERT INTO movie_finder.language VALUES ('be', 'bielorruso');
INSERT INTO movie_finder.language VALUES ('be_BY', 'bielorruso [Bielorrusia]');
INSERT INTO movie_finder.language VALUES ('bg', 'búlgaro');
INSERT INTO movie_finder.language VALUES ('bg_BG', 'búlgaro [Bulgaria]');
INSERT INTO movie_finder.language VALUES ('ca', 'catalán');
INSERT INTO movie_finder.language VALUES ('ca_ES', 'catalán [España]');
INSERT INTO movie_finder.language VALUES ('cs', 'checo');
INSERT INTO movie_finder.language VALUES ('cs_CZ', 'checo [Chequia]');
INSERT INTO movie_finder.language VALUES ('da', 'danés');
INSERT INTO movie_finder.language VALUES ('da_DK', 'danés [Dinamarca]');
INSERT INTO movie_finder.language VALUES ('de', 'alemán');
INSERT INTO movie_finder.language VALUES ('de_AT', 'alemán [Austria]');
INSERT INTO movie_finder.language VALUES ('de_CH', 'alemán [Suiza]');
INSERT INTO movie_finder.language VALUES ('de_DE', 'alemán [Alemania]');
INSERT INTO movie_finder.language VALUES ('de_LU', 'alemán [Luxemburgo]');
INSERT INTO movie_finder.language VALUES ('el', 'griego');
INSERT INTO movie_finder.language VALUES ('el_CY', 'griego [Chipre]');
INSERT INTO movie_finder.language VALUES ('el_GR', 'griego [Grecia]');
INSERT INTO movie_finder.language VALUES ('en', 'inglés');
INSERT INTO movie_finder.language VALUES ('en_AU', 'inglés [Australia]');
INSERT INTO movie_finder.language VALUES ('en_CA', 'inglés [Canadá]');
INSERT INTO movie_finder.language VALUES ('en_GB', 'inglés [Reino Unido]');
INSERT INTO movie_finder.language VALUES ('en_IE', 'inglés [Irlanda]');
INSERT INTO movie_finder.language VALUES ('en_IN', 'inglés [India]');
INSERT INTO movie_finder.language VALUES ('en_MT', 'inglés [Malta]');
INSERT INTO movie_finder.language VALUES ('en_NZ', 'inglés [Nueva Zelanda]');
INSERT INTO movie_finder.language VALUES ('en_PH', 'inglés [Filipinas]');
INSERT INTO movie_finder.language VALUES ('en_SG', 'inglés [Singapur]');
INSERT INTO movie_finder.language VALUES ('en_US', 'inglés [Estados Unidos]');
INSERT INTO movie_finder.language VALUES ('en_ZA', 'inglés [Sudáfrica]');
INSERT INTO movie_finder.language VALUES ('es', 'español');
INSERT INTO movie_finder.language VALUES ('es_AR', 'español [Argentina]');
INSERT INTO movie_finder.language VALUES ('es_BO', 'español [Bolivia]');
INSERT INTO movie_finder.language VALUES ('es_CL', 'español [Chile]');
INSERT INTO movie_finder.language VALUES ('es_CO', 'español [Colombia]');
INSERT INTO movie_finder.language VALUES ('es_CR', 'español [Costa Rica]');
INSERT INTO movie_finder.language VALUES ('es_DO', 'español [República Dominicana]');
INSERT INTO movie_finder.language VALUES ('es_EC', 'español [Ecuador]');
INSERT INTO movie_finder.language VALUES ('es_ES', 'español [España]');
INSERT INTO movie_finder.language VALUES ('es_GT', 'español [Guatemala]');
INSERT INTO movie_finder.language VALUES ('es_HN', 'español [Honduras]');
INSERT INTO movie_finder.language VALUES ('es_MX', 'español [México]');
INSERT INTO movie_finder.language VALUES ('es_NI', 'español [Nicaragua]');
INSERT INTO movie_finder.language VALUES ('es_PA', 'español [Panamá]');
INSERT INTO movie_finder.language VALUES ('es_PE', 'español [Perú]');
INSERT INTO movie_finder.language VALUES ('es_PR', 'español [Puerto Rico]');
INSERT INTO movie_finder.language VALUES ('es_PY', 'español [Paraguay]');
INSERT INTO movie_finder.language VALUES ('es_SV', 'español [El Salvador]');
INSERT INTO movie_finder.language VALUES ('es_US', 'español [Estados Unidos]');
INSERT INTO movie_finder.language VALUES ('es_UY', 'español [Uruguay]');
INSERT INTO movie_finder.language VALUES ('es_VE', 'español [Venezuela]');
INSERT INTO movie_finder.language VALUES ('et', 'estonio');
INSERT INTO movie_finder.language VALUES ('et_EE', 'estonio [Estonia]');
INSERT INTO movie_finder.language VALUES ('fi', 'finés');
INSERT INTO movie_finder.language VALUES ('fi_FI', 'finés [Finlandia]');
INSERT INTO movie_finder.language VALUES ('fr', 'francés');
INSERT INTO movie_finder.language VALUES ('fr_BE', 'francés [Bélgica]');
INSERT INTO movie_finder.language VALUES ('fr_CA', 'francés [Canadá]');
INSERT INTO movie_finder.language VALUES ('fr_CH', 'francés [Suiza]');
INSERT INTO movie_finder.language VALUES ('fr_FR', 'francés [Francia]');
INSERT INTO movie_finder.language VALUES ('fr_LU', 'francés [Luxemburgo]');
INSERT INTO movie_finder.language VALUES ('ga', 'irlandés');
INSERT INTO movie_finder.language VALUES ('ga_IE', 'irlandés [Irlanda]');
INSERT INTO movie_finder.language VALUES ('hi_IN', 'hindú [India]');
INSERT INTO movie_finder.language VALUES ('hr', 'croata');
INSERT INTO movie_finder.language VALUES ('hr_HR', 'croata [Croacia]');
INSERT INTO movie_finder.language VALUES ('hu', 'húngaro');
INSERT INTO movie_finder.language VALUES ('hu_HU', 'húngaro [Hungría]');
INSERT INTO movie_finder.language VALUES ('in', 'indonesio');
INSERT INTO movie_finder.language VALUES ('in_ID', 'indonesio [Indonesia]');
INSERT INTO movie_finder.language VALUES ('is', 'islandés');
INSERT INTO movie_finder.language VALUES ('is_IS', 'islandés [Islandia]');
INSERT INTO movie_finder.language VALUES ('it', 'italiano');
INSERT INTO movie_finder.language VALUES ('it_CH', 'italiano [Suiza]');
INSERT INTO movie_finder.language VALUES ('it_IT', 'italiano [Italia]');
INSERT INTO movie_finder.language VALUES ('iw', 'hebreo');
INSERT INTO movie_finder.language VALUES ('iw_IL', 'hebreo [Israel]');
INSERT INTO movie_finder.language VALUES ('ja', 'japonés');
INSERT INTO movie_finder.language VALUES ('ja_JP', 'japonés [Japón]');
INSERT INTO movie_finder.language VALUES ('ko', 'coreano');
INSERT INTO movie_finder.language VALUES ('ko_KR', 'coreano [Corea del Sur]');
INSERT INTO movie_finder.language VALUES ('lt', 'lituano');
INSERT INTO movie_finder.language VALUES ('lt_LT', 'lituano [Lituania]');
INSERT INTO movie_finder.language VALUES ('lv', 'letón');
INSERT INTO movie_finder.language VALUES ('lv_LV', 'letón [Letonia]');
INSERT INTO movie_finder.language VALUES ('mk', 'macedonio');
INSERT INTO movie_finder.language VALUES ('mk_MK', 'macedonio [Macedonia]');
INSERT INTO movie_finder.language VALUES ('ms', 'malayo');
INSERT INTO movie_finder.language VALUES ('ms_MY', 'malayo [Malasia]');
INSERT INTO movie_finder.language VALUES ('mt', 'maltés');
INSERT INTO movie_finder.language VALUES ('mt_MT', 'maltés [Malta]');
INSERT INTO movie_finder.language VALUES ('nl', 'neerlandés');
INSERT INTO movie_finder.language VALUES ('nl_BE', 'neerlandés [Bélgica]');
INSERT INTO movie_finder.language VALUES ('nl_NL', 'neerlandés [Holanda]');
INSERT INTO movie_finder.language VALUES ('no', 'noruego');
INSERT INTO movie_finder.language VALUES ('no_NO', 'noruego [Noruega]');
INSERT INTO movie_finder.language VALUES ('pl', 'polaco');
INSERT INTO movie_finder.language VALUES ('pl_PL', 'polaco [Polonia]');
INSERT INTO movie_finder.language VALUES ('pt', 'portugués');
INSERT INTO movie_finder.language VALUES ('pt_BR', 'portugués [Brasil]');
INSERT INTO movie_finder.language VALUES ('pt_PT', 'portugués [Portugal]');
INSERT INTO movie_finder.language VALUES ('ro', 'rumano');
INSERT INTO movie_finder.language VALUES ('ro_RO', 'rumano [Rumania]');
INSERT INTO movie_finder.language VALUES ('ru', 'ruso');
INSERT INTO movie_finder.language VALUES ('ru_RU', 'ruso [Rusia]');
INSERT INTO movie_finder.language VALUES ('sk', 'eslovaco');
INSERT INTO movie_finder.language VALUES ('sk_SK', 'eslovaco [Eslovaquia]');
INSERT INTO movie_finder.language VALUES ('sl', 'eslovenio');
INSERT INTO movie_finder.language VALUES ('sl_SI', 'eslovenio [Eslovenia]');
INSERT INTO movie_finder.language VALUES ('sq', 'albanés');
INSERT INTO movie_finder.language VALUES ('sq_AL', 'albanés [Albania]');
INSERT INTO movie_finder.language VALUES ('sr', 'serbio');
INSERT INTO movie_finder.language VALUES ('sr_BA', 'serbio [Bosnia y Hercegovina]');
INSERT INTO movie_finder.language VALUES ('sr_CS', 'serbio [Serbia y Montenegro]');
INSERT INTO movie_finder.language VALUES ('sr_ME', 'serbio [Montenegro]');
INSERT INTO movie_finder.language VALUES ('sr_RS', 'serbio [Serbia]');
INSERT INTO movie_finder.language VALUES ('sv', 'sueco');
INSERT INTO movie_finder.language VALUES ('sv_SE', 'sueco [Suecia]');
INSERT INTO movie_finder.language VALUES ('th', 'tailandés');
INSERT INTO movie_finder.language VALUES ('th_TH', 'tailandés [Tailandia]');
INSERT INTO movie_finder.language VALUES ('tr', 'turco');
INSERT INTO movie_finder.language VALUES ('tr_TR', 'turco [Turquía]');
INSERT INTO movie_finder.language VALUES ('uk', 'ucranio');
INSERT INTO movie_finder.language VALUES ('uk_UA', 'ucranio [Ucrania]');
INSERT INTO movie_finder.language VALUES ('vi', 'vietnamita');
INSERT INTO movie_finder.language VALUES ('vi_VN', 'vietnamita [Vietnam]');
INSERT INTO movie_finder.language VALUES ('zh', 'chino');
INSERT INTO movie_finder.language VALUES ('zh_CN', 'chino [China]');
INSERT INTO movie_finder.language VALUES ('zh_HK', 'chino [Hong Kong]');
INSERT INTO movie_finder.language VALUES ('zh_SG', 'chino [Singapur]');
INSERT INTO movie_finder.language VALUES ('zh_TW', 'chino [Taiwán]');