INSERT INTO movie_finder.reviewer (`user_name`) VALUES 
('drinkingturtle'),
('RueMorgue'),
('SD-4'),
('ryan_lynch'),
('Antithesys'),
('reesew18'),
('Philip_Pugh'),
('The Woof'),
('bootsy-4'),
('Smells_Like_Cheese'),
('tuhmartinez-phd'),
('Rusty-61'),
('Michael Carruthers'),
('Jason Morales'),
('the-evil-Jason Morales'),
('Benedict_Cumberbatch'),
('tPulpthatsfiction'),
('WiseFool'),
('sosodop'),
('Oro-Indiano'),
('Brundledan'),
('C-17'),
('andrew7'),
('kenjha'),
('dataconflossmoor'),
('capsize'),
('grizz2'),
('gregopego12'),
('leejgoldie'),
('Kronos-8'),
('MadiZone'),
('tagliaferrianthony'),
('FBCorey89'),
('ijtfalcon'),
('tonyf-2'),
('gorillaz-96353'),
('easy3456'),
('DTL'),
('Sean26'),
('Z-Dawg'),
('Adrian-32'),
('Fushigidane'),
('Zeke-36'),
('Grover-21'),
('Chalk'),
('joshWI'),
('donkrishna-dk'),
('TomatoFork'),
('riz-5');