

        INSERT INTO "Movies" VALUES (01, 'avatar',2005, 209, 'US', 01  );
        INSERT INTO "Movies" VALUES (02, 'the king ',2005, 90, 'US', 02  );
        INSERT INTO "Movies" VALUES (03, 'terminator',2009, 112, 'US', 03  );
        INSERT INTO "Movies" VALUES (04, 'the blues brothers',1980, 132, 'ES', 04  );
        INSERT INTO "Movies" VALUES (05, 'la isla',2005, 101, 'AM', 05  );
        INSERT INTO "Movies" VALUES (06, 'perros de paja',2005, 89, 'BE', 06  );
        INSERT INTO "Movies" VALUES (07, 'moros y cristianos ',1985, 135, 'BR', 07  );
        INSERT INTO "Movies" VALUES (08, 'chocolat',1971, 100, 'CA', 08  );
        INSERT INTO "Movies" VALUES (09, 'rain man',1987, 135, 'DE', 09  );
        INSERT INTO "Movies" VALUES (10, 'calabuch',2000, 103, 'CU', 10 );
        INSERT INTO "Movies" VALUES (11, 'trainspotting',1988, 97, 'CH', 11  );
        INSERT INTO "Movies" VALUES (12, 'taxi driver',1956, 98, 'US', 12  );
        INSERT INTO "Movies" VALUES (13, 'seven',1996, 145, 'US', 13  );
        INSERT INTO "Movies" VALUES (14, 'harold lloid',1995, 133, 'US', 14  );
        INSERT INTO "Movies" VALUES (15, 'codigo 46',2005, 107, 'EC', 15  );
        INSERT INTO "Movies" VALUES (16, 'el señor de los anillos',2001, 130, 'US', 16  );
        INSERT INTO "Movies" VALUES (17, 'Nosotros decimos',2001, 99, 'US', 17  );
        INSERT INTO "Movies" VALUES (18, 'El viaje de chihiro',2002, 107, 'CL', 18  );
        INSERT INTO "Movies" VALUES (19, 'ciudad de Dios',2002, 132, 'ES', 19  );
        INSERT INTO "Movies" VALUES (20, 'El señor de los anillos, el retorno del rey ',2003, 145, 'us', 20  );
        INSERT INTO "Movies" VALUES (21, 'Entre copas',2005, 107, 'EC', 21  );
        INSERT INTO "Movies" VALUES (22, 'la mejor juventud ',2006, 108, 'TL', 22  );
        INSERT INTO "Movies" VALUES (23, 'olvidate de mi',2004, 107, 'EC', 23  );
        INSERT INTO "Movies" VALUES (24, 'Munich',2005, 92, 'ES', 24  );
        INSERT INTO "Movies" VALUES (25, 'El laberinto del fauno',2006, 101, 'MX', 25  );
        INSERT INTO "Movies" VALUES (26, 'Hijos del los hombres',2006, 78, 'US', 26  );
        INSERT INTO "Movies" VALUES (27, 'ratatouille',2007, 122, 'AR', 27  );
        INSERT INTO "Movies" VALUES (28, 'Zodiac',2007, 101, 'US', 28  );
        INSERT INTO "Movies" VALUES (29, 'Wall-E',2008, 98, 'AR', 29  );
        INSERT INTO "Movies" VALUES (30, '4 meses, 3 semanas y dos dias ',2008, 123, 'EC', 30  );
        INSERT INTO "Movies" VALUES (31, 'Malditos bastardos',2009, 112, 'US', 31  );
        INSERT INTO "Movies" VALUES (32, 'La red social',2010, 133, 'US', 32  );
        INSERT INTO "Movies" VALUES (33, 'Drive',2011, 100, 'US', 33  );
        INSERT INTO "Movies" VALUES (34, 'La hora mas oscura',2012, 95, 'ES', 34  );
        INSERT INTO "Movies" VALUES (35, 'call me be your name',2018, 143, 'ES', 35  );
        
        INSERT INTO "Director" VALUES (01,'James Cameron');
        INSERT INTO "Director" VALUES (02,'Stanley Kubrick');
        INSERT INTO "Director" VALUES (03,'Quentin Tarantino');
        INSERT INTO "Director" VALUES (04,'Alfred Hitchcock');
        INSERT INTO "Director" VALUES (05,'Steven Spielberg');
        INSERT INTO "Director" VALUES (06,'Martin Scorsese');
        INSERT INTO "Director" VALUES (07,'Charles Chaplin');
        INSERT INTO "Director" VALUES (08,'Christopher Nolan');
        INSERT INTO "Director" VALUES (09,'FRancis Ford Coppola');
        INSERT INTO "Director" VALUES (10,'Clint Eastwood');
        INSERT INTO "Director" VALUES (11,'Tin Burton');
        INSERT INTO "Director" VALUES (12,'Billy Wilder');
        INSERT INTO "Director" VALUES (13,'Ridley Scott');
        INSERT INTO "Director" VALUES (14,'John Ford');
        INSERT INTO "Director" VALUES (15,'Woody Allen');
        INSERT INTO "Director" VALUES (16,'Peter Jackson');
        INSERT INTO "Director" VALUES (17,'Robert Zemeckis');
        INSERT INTO "Director" VALUES (18,'Orson Welles');
        INSERT INTO "Director" VALUES (19,'Roman Polanski');
        INSERT INTO "Director" VALUES (20,'John Huston');
        INSERT INTO "Director" VALUES (21,'Frank Capra');
        INSERT INTO "Director" VALUES (22,'Howard Hawks');
        INSERT INTO "Director" VALUES (23,'George Lucas');
        INSERT INTO "Director" VALUES (24,'David Lean');
        INSERT INTO "Director" VALUES (25,'William Wyler');

        INSERT INTO "Languages"VALUES (01,'English ', "EN");
        INSERT INTO "Languages"VALUES (02,' Afar ', "AA");
        INSERT INTO "Languages"VALUES (03,'Abkhazian ', "AB");
        INSERT INTO "Languages"VALUES (04,'Amharic ', "EN");
        INSERT INTO "Languages"VALUES (05,'Arabic ',"AM");
        INSERT INTO "Languages"VALUES (06,'Assamese ', "AS");
        INSERT INTO "Languages"VALUES (07,'Aymara ', "AY");
        INSERT INTO "Languages"VALUES (08,'Azerbaijani ', "AZ");
        INSERT INTO "Languages"VALUES (09,'Bashkir ', "BA");
        INSERT INTO "Languages"VALUES (10,'Belarusian ', "BE");
        INSERT INTO "Languages"VALUES (11,'Bulgarian', "BG");
        INSERT INTO "Languages"VALUES (12,'Bihari', "BH");
        INSERT INTO "Languages"VALUES (13,'Bislama ', "BI");
        INSERT INTO "Languages"VALUES (14,'Bengali/Bangla ', "BN");
        INSERT INTO "Languages"VALUES (15,'Tibetan ', "BO");
        INSERT INTO "Languages"VALUES (16,'Breton ',"BR");
        INSERT INTO "Languages"VALUES (17,'Catalan ', "CA");
        INSERT INTO "Languages"VALUES (18,'Corsican ', "CO");
        INSERT INTO "Languages"VALUES (19,'Czech ', "CS");
        INSERT INTO "Languages"VALUES (20,'Welsh ', "CY");
        INSERT INTO "Languages"VALUES (21,'Danish ', "DA");
        INSERT INTO "Languages"VALUES (22,'German ', "DE");
        INSERT INTO "Languages"VALUES (23,'Bhutani ', "DZ");
        INSERT INTO "Languages"VALUES (24,'Greek', "EL");
        INSERT INTO "Languages"VALUES (24,'Esperanto ', "EO");
        INSERT INTO "Languages"VALUES (26,'Spanish', "ES");
        INSERT INTO "Languages"VALUES (27,'Estonian', "ET");
        INSERT INTO "Languages"VALUES (28,'Basque', "EU");
        INSERT INTO "Languages"VALUES (29,'Persian', "FA");
        INSERT INTO "Languages"VALUES (30,'Finnish', "FI");
        INSERT INTO "Languages"VALUES (31,'Fiji',"FJ");
        INSERT INTO "Languages"VALUES (32,'Faeroese', "FO");
        INSERT INTO "Languages"VALUES (33,'French', "FR");
        INSERT INTO "Languages"VALUES (34,'Frisian', "FY");
        INSERT INTO "Languages"VALUES (35,'Irish', "GA");
        INSERT INTO "Languages"VALUES (36,'Scots/Gaelic', "GD");
        INSERT INTO "Languages"VALUES (37,'Galacian', "GL");
        INSERT INTO "Languages"VALUES (38,'Guarani', "GN");
        INSERT INTO "Languages"VALUES (39,'Gujarati', "GU");
        INSERT INTO "Languages"VALUES (40,'Hausa', "HA");
        INSERT INTO "Languages"VALUES (41,'Hindi', "HI");
        INSERT INTO "Languages"VALUES (42,'Croatian', "HR");
        INSERT INTO "Languages"VALUES (43,'Hungarian', "HU");
        INSERT INTO "Languages"VALUES (44,'Frisian', "FY");
        INSERT INTO "Languages"VALUES (45,'Armenian', "HY");
        INSERT INTO "Languages"VALUES (46,'Interlingua', "IA");
        INSERT INTO "Languages"VALUES (47,'Interlingue', "IE");
        INSERT INTO "Languages"VALUES (48,'Inupiak', "IK");
        INSERT INTO "Languages"VALUES (49,'Indonesian', "IK");
        INSERT INTO "Languages"VALUES (50,'Icelandic', "IS");
        INSERT INTO "Languages"VALUES (51,'Italian', "IT");
        INSERT INTO "Languages"VALUES (53,'Japanese', "JA");
        INSERT INTO "Languages"VALUES (54,'Yiddish', "JI");
        INSERT INTO "Languages"VALUES (55,'Javanese', "JW");
        INSERT INTO "Languages"VALUES (56,'Georgian', "KA");
        INSERT INTO "Languages"VALUES (57,'Kazakh', "KK");
        INSERT INTO "Languages"VALUES (58,'Greenlandic', "KL");
        INSERT INTO "Languages"VALUES (59,'Cambodian', "KM");
        INSERT INTO "Languages"VALUES (60,'Kannada', "KN");
        INSERT INTO "Languages"VALUES (61,'Korean', "KO");
        INSERT INTO "Languages"VALUES (62,'Kashmiri', "KS");
        INSERT INTO "Languages"VALUES (63,'Kurdish', "KU");
        INSERT INTO "Languages"VALUES (64,'Kirghiz', "KY");
        INSERT INTO "Languages"VALUES (65,'Latin', "LA");
        INSERT INTO "Languages"VALUES (66,'Lingala', "LN");
        INSERT INTO "Languages"VALUES (67,'Laothian', "LO");
        INSERT INTO "Languages"VALUES (68,'Lithuanian', "LT");
        INSERT INTO "Languages"VALUES (69,'Latvian/Lettish', "LV");
        INSERT INTO "Languages"VALUES (70,'Malagasy', "MG");
        INSERT INTO "Languages"VALUES (71,'Maori', "MI");
        INSERT INTO "Languages"VALUES (72,'Macedonian', "MK");
        INSERT INTO "Languages"VALUES (73,'Malayalam', "ML");
        INSERT INTO "Languages"VALUES (74,'Mongolian', "MN");
        INSERT INTO "Languages"VALUES (75,'Moldavian', "MO");
        INSERT INTO "Languages"VALUES (76,'Marathi', "MR");
        INSERT INTO "Languages"VALUES (77,'Malay', "MS");
        INSERT INTO "Languages"VALUES (78,'Maltese', "MT");
        INSERT INTO "Languages"VALUES (79,'Burmese', "MY");
        INSERT INTO "Languages"VALUES (80,'Nauru', "NA");
        INSERT INTO "Languages"VALUES (81,'Nepali', "NE");
        INSERT INTO "Languages"VALUES (82,'Dutch', "NL");
        INSERT INTO "Languages"VALUES (83,'Norwegina', "NO");
        INSERT INTO "Languages"VALUES (84,'Occitan', "OC");
        INSERT INTO "Languages" VALUES(85, '(Afan)/Oromoor/Oriya', 'om');
        INSERT INTO "Languages" VALUES(86, 'Punjabi', 'pa');
        INSERT INTO "Languages" VALUES(87, 'Polish', 'pl');
        INSERT INTO "Languages" VALUES(88, 'Pashto/Pushto', 'ps');
        INSERT INTO "Languages" VALUES(89, 'Portuguese', 'pt');
        INSERT INTO "Languages" VALUES(90, 'Quechua', 'qu');
        INSERT INTO "Languages" VALUES(91, 'Rhaeto-Romance', 'rm');
        INSERT INTO "Languages" VALUES(92, 'Kirundi', 'rn');
        INSERT INTO "Languages" VALUES(93, 'Romanian', 'ro');
        INSERT INTO "Languages" VALUES(94, 'Russian', 'ru');
        INSERT INTO "Languages" VALUES(95, 'Kinyarwanda', 'rw');
        INSERT INTO "Languages" VALUES(96, 'Sanskrit', 'sa');
        INSERT INTO "Languages" VALUES(97, 'Sindhi', 'sd');
        INSERT INTO "Languages" VALUES(98, 'Sangro', 'sg');
        INSERT INTO "Languages" VALUES(99, 'Serbo-Croatian', 'sh');
        INSERT INTO "Languages" VALUES(100, 'Singhalese', 'si');
        INSERT INTO "Languages" VALUES(101, 'Slovak', 'sk');
        INSERT INTO "Languages" VALUES(102, 'Slovenian', 'sl');
        INSERT INTO "Languages" VALUES(103, 'Samoan', 'sm');
        INSERT INTO "Languages" VALUES(104, 'Shona', 'sn');
        INSERT INTO "Languages" VALUES(105, 'Somali', 'so');
        INSERT INTO "Languages" VALUES(106, 'Albanian', 'sq');
        INSERT INTO "Languages" VALUES(107, 'Serbian', 'sr');
        INSERT INTO "Languages" VALUES(108, 'Siswati', 'ss');
        INSERT INTO "Languages" VALUES(109, 'Sesotho', 'st');
        INSERT INTO "Languages" VALUES(110, 'Sundanese', 'su');
        INSERT INTO "Languages" VALUES(111, 'Swedish', 'sv');
        INSERT INTO "Languages" VALUES(112, 'Swahili', 'sw');
        INSERT INTO "Languages" VALUES(113, 'Tamil', 'ta');
        INSERT INTO "Languages" VALUES(114, 'Telugu', 'te');
        INSERT INTO "Languages" VALUES(115, 'Tajik', 'tg');
        INSERT INTO "Languages" VALUES(116, 'Thai', 'th');
        INSERT INTO "Languages" VALUES(117, 'Tigrinya', 'ti');
        INSERT INTO "Languages" VALUES(118, 'Turkmen', 'tk');
        INSERT INTO "Languages" VALUES(119, 'Tagalog', 'tl');
        INSERT INTO "Languages" VALUES(120, 'Setswana', 'tn');
        INSERT INTO "Languages" VALUES(121, 'Tonga', 'to');
        INSERT INTO "Languages" VALUES(122, 'Turkish', 'tr');
        INSERT INTO "Languages" VALUES(123, 'Tsonga', 'ts');
        INSERT INTO "Languages" VALUES(124, 'Tatar', 'tt');
        INSERT INTO "Languages" VALUES(125, 'Twi', 'tw');
        INSERT INTO "Languages" VALUES(126, 'Ukrainian', 'uk');
        INSERT INTO "Languages" VALUES(127, 'Urdu', 'ur');
        INSERT INTO "Languages" VALUES(128, 'Uzbek', 'uz');
        INSERT INTO "Languages" VALUES(129, 'Vietnamese', 'vi');
        INSERT INTO "Languages" VALUES(130, 'Volapuk', 'vo');
        INSERT INTO "Languages" VALUES(131, 'Wolof', 'wo');
        INSERT INTO "Languages" VALUES(132, 'Xhosa', 'xh');
        INSERT INTO "Languages" VALUES(133, 'Yoruba', 'yo');
        INSERT INTO "Languages" VALUES(134, 'Chinese', 'zh');
        INSERT INTO "Languages" VALUES(135, 'Zulu', 'zu');

        INSERT INTO "Countries" VALUES ('AF', 'Afghanistan');
        INSERT INTO "Countries" VALUES ('AL', 'Albania');
        INSERT INTO "Countries" VALUES ('DZ', 'Algeria');
        INSERT INTO "Countries" VALUES ('DS', 'American Samoa');
        INSERT INTO "Countries" VALUES ('AD', 'Andorra');
        INSERT INTO "Countries" VALUES ('AO', 'Angola');
        INSERT INTO "Countries" VALUES ('AI', 'Anguilla');
        INSERT INTO "Countries" VALUES ('AQ', 'Antarctica');
        INSERT INTO "Countries" VALUES ('AG', 'Antigua and Barbuda');
        INSERT INTO "Countries" VALUES ('AR', 'Argentina');
        INSERT INTO "Countries" VALUES ('AM', 'Armenia');
        INSERT INTO "Countries" VALUES ('AW', 'Aruba');
        INSERT INTO "Countries" VALUES ('AU', 'Australia');
        INSERT INTO "Countries" VALUES ('AT', 'Austria');
        INSERT INTO "Countries" VALUES ('AZ', 'Azerbaijan');
        INSERT INTO "Countries" VALUES ('BS', 'Bahamas');
        INSERT INTO "Countries" VALUES ('BH', 'Bahrain');
        INSERT INTO "Countries" VALUES ('BD', 'Bangladesh');
        INSERT INTO "Countries" VALUES ('BB', 'Barbados');
        INSERT INTO "Countries" VALUES ('BY', 'Belarus');
        INSERT INTO "Countries" VALUES ('BE', 'Belgium');
        INSERT INTO "Countries" VALUES ('BZ', 'Belize');
        INSERT INTO "Countries" VALUES ('BJ', 'Benin');
        INSERT INTO "Countries" VALUES ('BM', 'Bermuda');
        INSERT INTO "Countries" VALUES ('BT', 'Bhutan');
        INSERT INTO "Countries" VALUES ('BO', 'Bolivia');
        INSERT INTO "Countries" VALUES ('BA', 'Bosnia and Herzegovina');
        INSERT INTO "Countries" VALUES ('BW', 'Botswana');
        INSERT INTO "Countries" VALUES ('BV', 'Bouvet Island');
        INSERT INTO "Countries" VALUES ('BR', 'Brazil');
        INSERT INTO "Countries" VALUES ('IO', 'British Indian Ocean Territory');
        INSERT INTO "Countries" VALUES ('BN', 'Brunei Darussalam');
        INSERT INTO "Countries" VALUES ('BG', 'Bulgaria');
        INSERT INTO "Countries" VALUES ('BF', 'Burkina Faso');
        INSERT INTO "Countries" VALUES ('BI', 'Burundi');
        INSERT INTO "Countries" VALUES ('KH', 'Cambodia');
        INSERT INTO "Countries" VALUES ('CM', 'Cameroon');
        INSERT INTO "Countries" VALUES ('CA', 'Canada');
        INSERT INTO "Countries" VALUES ('CV', 'Cape Verde');
        INSERT INTO "Countries" VALUES ('KY', 'Cayman Islands');
        INSERT INTO "Countries" VALUES ('CF', 'Central African Republic');
        INSERT INTO "Countries" VALUES ('TD', 'Chad');
        INSERT INTO "Countries" VALUES ('CL', 'Chile');
        INSERT INTO "Countries" VALUES ('CN', 'China');
        INSERT INTO "Countries" VALUES ('CX', 'Christmas Island');
        INSERT INTO "Countries" VALUES ('CC', 'Cocos (Keeling) Islands');
        INSERT INTO "Countries" VALUES ('CO', 'Colombia');
        INSERT INTO "Countries" VALUES ('KM', 'Comoros');
        INSERT INTO "Countries" VALUES ('CG', 'Congo');
        INSERT INTO "Countries" VALUES ('CK', 'Cook Islands');
        INSERT INTO "Countries" VALUES ('CR', 'Costa Rica');
        INSERT INTO "Countries" VALUES ('HR', 'Croatia (Hrvatska)');
        INSERT INTO "Countries" VALUES ('CU', 'Cuba');
        INSERT INTO "Countries" VALUES ('CY', 'Cyprus');
        INSERT INTO "Countries" VALUES ('CZ', 'Czech Republic');
        INSERT INTO "Countries" VALUES ('DK', 'Denmark');
        INSERT INTO "Countries" VALUES ('DJ', 'Djibouti');
        INSERT INTO "Countries" VALUES ('DM', 'Dominica');
        INSERT INTO "Countries" VALUES ('DO', 'Dominican Republic');
        INSERT INTO "Countries" VALUES ('TP', 'East Timor');
        INSERT INTO "Countries" VALUES ('EC', 'Ecuador');
        INSERT INTO "Countries" VALUES ('EG', 'Egypt');
        INSERT INTO "Countries" VALUES ('SV', 'El Salvador');
        INSERT INTO "Countries" VALUES ('GQ', 'Equatorial Guinea');
        INSERT INTO "Countries" VALUES ('ER', 'Eritrea');
        INSERT INTO "Countries" VALUES ('EE', 'Estonia');
        INSERT INTO "Countries" VALUES ('ET', 'Ethiopia');
        INSERT INTO "Countries" VALUES ('FK', 'Falkland Islands (Malvinas)');
        INSERT INTO "Countries" VALUES ('FO', 'Faroe Islands');
        INSERT INTO "Countries" VALUES ('FJ', 'Fiji');
        INSERT INTO "Countries" VALUES ('FI', 'Finland');
        INSERT INTO "Countries" VALUES ('FR', 'France');
        INSERT INTO "Countries" VALUES ('FX', 'France, Metropolitan');
        INSERT INTO "Countries" VALUES ('GF', 'French Guiana');
        INSERT INTO "Countries" VALUES ('PF', 'French Polynesia');
        INSERT INTO "Countries" VALUES ('TF', 'French Southern Territories');
        INSERT INTO "Countries" VALUES ('GA', 'Gabon');
        INSERT INTO "Countries" VALUES ('GM', 'Gambia');
        INSERT INTO "Countries" VALUES ('GE', 'Georgia');
        INSERT INTO "Countries" VALUES ('DE', 'Germany');
        INSERT INTO "Countries" VALUES ('GH', 'Ghana');
        INSERT INTO "Countries" VALUES ('GI', 'Gibraltar');
        INSERT INTO "Countries" VALUES ('GK', 'Guernsey');
        INSERT INTO "Countries" VALUES ('GR', 'Greece');
        INSERT INTO "Countries" VALUES ('GL', 'Greenland');
        INSERT INTO "Countries" VALUES ('GD', 'Grenada');
        INSERT INTO "Countries" VALUES ('GP', 'Guadeloupe');
        INSERT INTO "Countries" VALUES ('GU', 'Guam');
        INSERT INTO "Countries" VALUES ('GT', 'Guatemala');
        INSERT INTO "Countries" VALUES ('GN', 'Guinea');
        INSERT INTO "Countries" VALUES ('GW', 'Guinea-Bissau');
        INSERT INTO "Countries" VALUES ('GY', 'Guyana');
        INSERT INTO "Countries" VALUES ('HT', 'Haiti');
        INSERT INTO "Countries" VALUES ('HM', 'Heard and Mc Donald Islands');
        INSERT INTO "Countries" VALUES ('HN', 'Honduras');
        INSERT INTO "Countries" VALUES ('HK', 'Hong Kong');
        INSERT INTO "Countries" VALUES ('HU', 'Hungary');
        INSERT INTO "Countries" VALUES ('IS', 'Iceland');
        INSERT INTO "Countries" VALUES ('IN', 'India');
        INSERT INTO "Countries" VALUES ('IM', 'Isle of Man');
        INSERT INTO "Countries" VALUES ('ID', 'Indonesia');
        INSERT INTO "Countries" VALUES ('IR', 'Iran (Islamic Republic of)');
        INSERT INTO "Countries" VALUES ('IQ', 'Iraq');
        INSERT INTO "Countries" VALUES ('IE', 'Ireland');
        INSERT INTO "Countries" VALUES ('IL', 'Israel');
        INSERT INTO "Countries" VALUES ('IT', 'Italy');
        INSERT INTO "Countries" VALUES ('CI', 'Ivory Coast');
        INSERT INTO "Countries" VALUES ('JE', 'Jersey');
        INSERT INTO "Countries" VALUES ('JM', 'Jamaica');
        INSERT INTO "Countries" VALUES ('JP', 'Japan');
        INSERT INTO "Countries" VALUES ('JO', 'Jordan');
        INSERT INTO "Countries" VALUES ('KZ', 'Kazakhstan');
        INSERT INTO "Countries" VALUES ('KE', 'Kenya');
        INSERT INTO "Countries" VALUES ('KI', 'Kiribati');
        INSERT INTO "Countries" VALUES ('KP', 'Korea, Democratic People''s Republic of');
        INSERT INTO "Countries" VALUES ('KR', 'Korea, Republic of');
        INSERT INTO "Countries" VALUES ('XK', 'Kosovo');
        INSERT INTO "Countries" VALUES ('KW', 'Kuwait');
        INSERT INTO "Countries" VALUES ('KG', 'Kyrgyzstan');
        INSERT INTO "Countries" VALUES ('LA', 'Lao People''s Democratic Republic');
        INSERT INTO "Countries" VALUES ('LV', 'Latvia');
        INSERT INTO "Countries" VALUES ('LB', 'Lebanon');
        INSERT INTO "Countries" VALUES ('LS', 'Lesotho');
        INSERT INTO "Countries" VALUES ('LR', 'Liberia');
        INSERT INTO "Countries" VALUES ('LY', 'Libyan Arab Jamahiriya');
        INSERT INTO "Countries" VALUES ('LI', 'Liechtenstein');
        INSERT INTO "Countries" VALUES ('LT', 'Lithuania');
        INSERT INTO "Countries" VALUES ('LU', 'Luxembourg');
        INSERT INTO "Countries" VALUES ('MO', 'Macau');
        INSERT INTO "Countries" VALUES ('MK', 'Macedonia');
        INSERT INTO "Countries" VALUES ('MG', 'Madagascar');
        INSERT INTO "Countries" VALUES ('MW', 'Malawi');
        INSERT INTO "Countries" VALUES ('MY', 'Malaysia');
        INSERT INTO "Countries" VALUES ('MV', 'Maldives');
        INSERT INTO "Countries" VALUES ('ML', 'Mali');
        INSERT INTO "Countries" VALUES ('MT', 'Malta');
        INSERT INTO "Countries" VALUES ('MH', 'Marshall Islands');
        INSERT INTO "Countries" VALUES ('MQ', 'Martinique');
        INSERT INTO "Countries" VALUES ('MR', 'Mauritania');
        INSERT INTO "Countries" VALUES ('MU', 'Mauritius');
        INSERT INTO "Countries" VALUES ('TY', 'Mayotte');
        INSERT INTO "Countries" VALUES ('MX', 'Mexico');
        INSERT INTO "Countries" VALUES ('FM', 'Micronesia, Federated States of');
        INSERT INTO "Countries" VALUES ('MD', 'Moldova, Republic of');
        INSERT INTO "Countries" VALUES ('MC', 'Monaco');
        INSERT INTO "Countries" VALUES ('MN', 'Mongolia');
        INSERT INTO "Countries" VALUES ('ME', 'Montenegro');
        INSERT INTO "Countries" VALUES ('MS', 'Montserrat');
        INSERT INTO "Countries" VALUES ('MA', 'Morocco');
        INSERT INTO "Countries" VALUES ('MZ', 'Mozambique');
        INSERT INTO "Countries" VALUES ('MM', 'Myanmar');
        INSERT INTO "Countries" VALUES ('NA', 'Namibia');
        INSERT INTO "Countries" VALUES ('NR', 'Nauru');
        INSERT INTO "Countries" VALUES ('NP', 'Nepal');
        INSERT INTO "Countries" VALUES ('NL', 'Netherlands');
        INSERT INTO "Countries" VALUES ('AN', 'Netherlands Antilles');
        INSERT INTO "Countries" VALUES ('NC', 'New Caledonia');
        INSERT INTO "Countries" VALUES ('NZ', 'New Zealand');
        INSERT INTO "Countries" VALUES ('NI', 'Nicaragua');
        INSERT INTO "Countries" VALUES ('NE', 'Niger');
        INSERT INTO "Countries" VALUES ('NG', 'Nigeria');
        INSERT INTO "Countries" VALUES ('NU', 'Niue');
        INSERT INTO "Countries" VALUES ('NF', 'Norfolk Island');
        INSERT INTO "Countries" VALUES ('MP', 'Northern Mariana Islands');
        INSERT INTO "Countries" VALUES ('NO', 'Norway');
        INSERT INTO "Countries" VALUES ('OM', 'Oman');
        INSERT INTO "Countries" VALUES ('PK', 'Pakistan');
        INSERT INTO "Countries" VALUES ('PW', 'Palau');
        INSERT INTO "Countries" VALUES ('PS', 'Palestine');
        INSERT INTO "Countries" VALUES ('PA', 'Panama');
        INSERT INTO "Countries" VALUES ('PG', 'Papua New Guinea');
        INSERT INTO "Countries" VALUES ('PY', 'Paraguay');
        INSERT INTO "Countries" VALUES ('PE', 'Peru');
        INSERT INTO "Countries" VALUES ('PH', 'Philippines');
        INSERT INTO "Countries" VALUES ('PN', 'Pitcairn');
        INSERT INTO "Countries" VALUES ('PL', 'Poland');
        INSERT INTO "Countries" VALUES ('PT', 'Portugal');
        INSERT INTO "Countries" VALUES ('PR', 'Puerto Rico');
        INSERT INTO "Countries" VALUES ('QA', 'Qatar');
        INSERT INTO "Countries" VALUES ('RE', 'Reunion');
        INSERT INTO "Countries" VALUES ('RO', 'Romania');
        INSERT INTO "Countries" VALUES ('RU', 'Russian Federation');
        INSERT INTO "Countries" VALUES ('RW', 'Rwanda');
        INSERT INTO "Countries" VALUES ('KN', 'Saint Kitts and Nevis');
        INSERT INTO "Countries" VALUES ('LC', 'Saint Lucia');
        INSERT INTO "Countries" VALUES ('VC', 'Saint Vincent and the Grenadines');
        INSERT INTO "Countries" VALUES ('WS', 'Samoa');
        INSERT INTO "Countries" VALUES ('SM', 'San Marino');
        INSERT INTO "Countries" VALUES ('ST', 'Sao Tome and Principe');
        INSERT INTO "Countries" VALUES ('SA', 'Saudi Arabia');
        INSERT INTO "Countries" VALUES ('SN', 'Senegal');
        INSERT INTO "Countries" VALUES ('RS', 'Serbia');
        INSERT INTO "Countries" VALUES ('SC', 'Seychelles');
        INSERT INTO "Countries" VALUES ('SL', 'Sierra Leone');
        INSERT INTO "Countries" VALUES ('SG', 'Singapore');
        INSERT INTO "Countries" VALUES ('SK', 'Slovakia');
        INSERT INTO "Countries" VALUES ('SI', 'Slovenia');
        INSERT INTO "Countries" VALUES ('SB', 'Solomon Islands');
        INSERT INTO "Countries" VALUES ('SO', 'Somalia');
        INSERT INTO "Countries" VALUES ('ZA', 'South Africa');
        INSERT INTO "Countries" VALUES ('GS', 'South Georgia South Sandwich Islands');
        INSERT INTO "Countries" VALUES ('SS', 'South Sudan');
        INSERT INTO "Countries" VALUES ('ES', 'Spain');
        INSERT INTO "Countries" VALUES ('LK', 'Sri Lanka');
        INSERT INTO "Countries" VALUES ('SH', 'St. Helena');
        INSERT INTO "Countries" VALUES ('PM', 'St. Pierre and Miquelon');
        INSERT INTO "Countries" VALUES ('SD', 'Sudan');
        INSERT INTO "Countries" VALUES ('SR', 'Suriname');
        INSERT INTO "Countries" VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
        INSERT INTO "Countries" VALUES ('SZ', 'Swaziland');
        INSERT INTO "Countries" VALUES ('SE', 'Sweden');
        INSERT INTO "Countries" VALUES ('CH', 'Switzerland');
        INSERT INTO "Countries" VALUES ('SY', 'Syrian Arab Republic');
        INSERT INTO "Countries" VALUES ('TW', 'Taiwan');
        INSERT INTO "Countries" VALUES ('TJ', 'Tajikistan');
        INSERT INTO "Countries" VALUES ('TZ', 'Tanzania, United Republic of');
        INSERT INTO "Countries" VALUES ('TH', 'Thailand');
        INSERT INTO "Countries" VALUES ('TG', 'Togo');
        INSERT INTO "Countries" VALUES ('TK', 'Tokelau');
        INSERT INTO "Countries" VALUES ('TO', 'Tonga');
        INSERT INTO "Countries" VALUES ('TT', 'Trinidad and Tobago');
        INSERT INTO "Countries" VALUES ('TN', 'Tunisia');
        INSERT INTO "Countries" VALUES ('TR', 'Turkey');
        INSERT INTO "Countries" VALUES ('TM', 'Turkmenistan');
        INSERT INTO "Countries" VALUES ('TC', 'Turks and Caicos Islands');
        INSERT INTO "Countries" VALUES ('TV', 'Tuvalu');
        INSERT INTO "Countries" VALUES ('UG', 'Uganda');
        INSERT INTO "Countries" VALUES ('UA', 'Ukraine');
        INSERT INTO "Countries" VALUES ('AE', 'United Arab Emirates');
        INSERT INTO "Countries" VALUES ('GB', 'United Kingdom');
        INSERT INTO "Countries" VALUES ('US', 'United States');
        INSERT INTO "Countries" VALUES ('UM', 'United States minor outlying islands');
        INSERT INTO "Countries" VALUES ('UY', 'Uruguay');
        INSERT INTO "Countries" VALUES ('UZ', 'Uzbekistan');
        INSERT INTO "Countries" VALUES ('VU', 'Vanuatu');
        INSERT INTO "Countries" VALUES ('VA', 'Vatican City State');
        INSERT INTO "Countries" VALUES ('VE', 'Venezuela');
        INSERT INTO "Countries" VALUES ('VN', 'Vietnam');
        INSERT INTO "Countries" VALUES ('VG', 'Virgin Islands (British)');
        INSERT INTO "Countries" VALUES ('VI', 'Virgin Islands (U.S.)');
        INSERT INTO "Countries" VALUES ('WF', 'Wallis and Futuna Islands');
        INSERT INTO "Countries" VALUES ('EH', 'Western Sahara');
        INSERT INTO "Countries" VALUES ('YE', 'Yemen');
        INSERT INTO "Countries" VALUES ('ZR', 'Zaire');
        INSERT INTO "Countries" VALUES ('ZM', 'Zambia');
        INSERT INTO "Countries" VALUES ('ZW', 'Zimbabwe');

        INSERT INTO ."Participants" VALUES(01, 'James Stewart');
        INSERT INTO ."Participants" VALUES(02, 'Deborah Kerr');
        INSERT INTO ."Participants" VALUES(03, 'Peter Otoole');
        INSERT INTO ."Participants" VALUES(04, 'Robert De Niro');
        INSERT INTO ."Participants" VALUES(05, 'F. Murray Abraham');
        INSERT INTO ."Participants" VALUES(06, 'Harrison Ford');
        INSERT INTO ."Participants" VALUES(07, 'Nicole Kidman');
        INSERT INTO ."Participants" VALUES(08, 'Stephen Baldwin');
        INSERT INTO ."Participants" VALUES(09, 'Jack Nocholson');
        INSERT INTO ."Participants" VALUES(10, 'Will Smith');
        INSERT INTO ."Participants" VALUES(11, 'Johnny Depp');
        INSERT INTO ."Participants" VALUES(12, 'Adam Sandler');
        INSERT INTO ."Participants" VALUES(13, 'Vin Diesel');
        INSERT INTO ."Participants" VALUES(14, 'Jackie Chan');
        INSERT INTO ."Participants" VALUES(15, 'Morgan Freeman');
        INSERT INTO ."Participants" VALUES(16, 'Angelina Jolie');
        INSERT INTO ."Participants" VALUES(17, 'Robin Williams');
        INSERT INTO ."Participants" VALUES(18, 'Leonardo Dicaprio');
        INSERT INTO ."Participants" VALUES(19, 'Jim Carrey');
        INSERT INTO ."Participants" VALUES(20, 'Nicholas Cage');
        INSERT INTO ."Participants" VALUES(21, 'Bruce Willis');
        INSERT INTO ."Participants" VALUES(22, 'Sandra Bullock');
        INSERT INTO ."Participants" VALUES(23, 'Tom Cruise');
        INSERT INTO ."Participants" VALUES(24, 'Cameron Diaz');
        INSERT INTO ."Participants" VALUES(25, 'Silvestre Stallone');
        INSERT INTO ."Participants" VALUES(26, 'Tom Hanks');
        INSERT INTO ."Participants" VALUES(27, 'Eddie Murphy');
        INSERT INTO ."Participants" VALUES(28, 'Scarlett Johansson');
        INSERT INTO ."Participants" VALUES(29, 'Robert de Niro');
        INSERT INTO ."Participants" VALUES(30, 'Ben Stiller');
        INSERT INTO ."Participants" VALUES(31, 'Julia Roberts');
        INSERT INTO ."Participants" VALUES(32, 'Owen Wilson');
        INSERT INTO ."Participants" VALUES(33, 'Megan Fox');
        INSERT INTO ."Participants" VALUES(34, 'Jack Black');

        INSERT INTO "genres" VALUES(01, 'Comedy');
        INSERT INTO "genres" VALUES(02, 'SCI-FI');
        INSERT INTO "genres" VALUES(03, 'Horror');
        INSERT INTO "genres" VALUES(04, 'Romance');
        INSERT INTO "genres" VALUES(05, 'Action');
        INSERT INTO "genres" VALUES(06, 'Thriller');
        INSERT INTO "genres" VALUES(07, 'Drama');
        INSERT INTO "genres" VALUES(08, 'Mystery');
        INSERT INTO "genres" VALUES(09, 'Crime');
        INSERT INTO "genres" VALUES(10, 'Animation');
        INSERT INTO "genres" VALUES(11, 'Adventure');
        INSERT INTO "genres" VALUES(12, 'Fantasy');
        INSERT INTO "genres" VALUES(13, 'SuperHero');
        INSERT INTO "genres" VALUES(14, 'Musical');
        INSERT INTO "genres" VALUES(15, 'Westerns');

        INSERT INTO "roles" VALUES(01, 'Main Actor');
        INSERT INTO "roles" VALUES(02, 'Secondary Actor');

        INSERT INTO "Ratings" VALUES(01, 01,08,'Me gusto mucho la pelicula ');
        INSERT INTO "Ratings" VALUES(02, 02,02,'la pelicula es horrible ');
        INSERT INTO "Ratings" VALUES(03, 03,10,'es la mejor pelicula que he visto');
        INSERT INTO "Ratings" VALUES(04, 04,08,'Me gusto mucho la pelicula ');
        INSERT INTO "Ratings" VALUES(05, 05,09,'la pelicula estuvo regular');
        INSERT INTO "Ratings" VALUES(06, 06,08,'Me gusto mucho la pelicula ');
        INSERT INTO "Ratings" VALUES(07, 07,04,'No me gustaron los actores');
        INSERT INTO "Ratings" VALUES(08, 08,06,'no estuvo ni buena ni mala ');
        INSERT INTO "Ratings" VALUES(09, 09,08,'Me gusto mucho la pelicula ');
        INSERT INTO "Ratings" VALUES(10, 10,07,'pudo ser mejor  ');
        INSERT INTO "Ratings" VALUES(11, 11,04,'no me guso casi nada ');
        INSERT INTO "Ratings" VALUES(12, 12,06,'pudo ser mejor  ');
        INSERT INTO "Ratings" VALUES(13, 13,05,'no me gustaron los efectos especiales  ');
        INSERT INTO "Ratings" VALUES(14, 14,02,'no me gusto par nada ');
        INSERT INTO "Ratings" VALUES(15, 15,07,'me gusto, pero no tanto  ');
        
        INSERT INTO "Genero_Movies" VALUES(01, 07);
        INSERT INTO "Genero_Movies" VALUES(02, 07);
        INSERT INTO "Genero_Movies" VALUES(03, 01);
        INSERT INTO "Genero_Movies" VALUES(04, 07);
        INSERT INTO "Genero_Movies" VALUES(05, 05);
        INSERT INTO "Genero_Movies" VALUES(06, 06);
        INSERT INTO "Genero_Movies" VALUES(07, 09);
        INSERT INTO "Genero_Movies" VALUES(08, 04);
        INSERT INTO "Genero_Movies" VALUES(09, 07);
        INSERT INTO "Genero_Movies" VALUES(10, 06);
        INSERT INTO "Genero_Movies" VALUES(11, 01);
        INSERT INTO "Genero_Movies" VALUES(12, 02);
        INSERT INTO "Genero_Movies" VALUES(13, 04);
        INSERT INTO "Genero_Movies" VALUES(14, 07);
        INSERT INTO "Genero_Movies" VALUES(15, 01);
        INSERT INTO "Genero_Movies" VALUES(16, 06);
        INSERT INTO "Genero_Movies" VALUES(17, 03);
        INSERT INTO "Genero_Movies" VALUES(18, 02);
        INSERT INTO "Genero_Movies" VALUES(19, 09);
        INSERT INTO "Genero_Movies" VALUES(20, 14);
        INSERT INTO "Genero_Movies" VALUES(21, 15);
        INSERT INTO "Genero_Movies" VALUES(22, 11);
        INSERT INTO "Genero_Movies" VALUES(23, 13);
        INSERT INTO "Genero_Movies" VALUES(24, 15);
        INSERT INTO "Genero_Movies" VALUES(25, 12);
        INSERT INTO "Genero_Movies" VALUES(26, 13);
        INSERT INTO "Genero_Movies" VALUES(27, 11);
        INSERT INTO "Genero_Movies" VALUES(28, 03);
        INSERT INTO "Genero_Movies" VALUES(29, 09);
        INSERT INTO "Genero_Movies" VALUES(30, 05);
        INSERT INTO "Genero_Movies" VALUES(31, 11);
        INSERT INTO "Genero_Movies" VALUES(31, 14);
        INSERT INTO "Genero_Movies" VALUES(33, 13);
        INSERT INTO "Genero_Movies" VALUES(34, 14);
        INSERT INTO "Genero_Movies" VALUES(35, 07);

        INSERT INTO "Roles_Movies" VALUES (01, 01);
        INSERT INTO "Roles_Movies" VALUES (01, 02);
        INSERT INTO "Roles_Movies" VALUES (02, 03);
        INSERT INTO "Roles_Movies" VALUES (02, 04);
        INSERT INTO "Roles_Movies" VALUES (02, 05);
        INSERT INTO "Roles_Movies" VALUES (01, 06);
        INSERT INTO "Roles_Movies" VALUES (01, 07);
        INSERT INTO "Roles_Movies" VALUES (02, 08);
        INSERT INTO "Roles_Movies" VALUES (01, 09);
        INSERT INTO "Roles_Movies" VALUES (02, 10);
        INSERT INTO "Roles_Movies" VALUES (01, 11);
        INSERT INTO "Roles_Movies" VALUES (02, 12);
        INSERT INTO "Roles_Movies" VALUES (02, 13);
        INSERT INTO "Roles_Movies" VALUES (01, 14);
        INSERT INTO "Roles_Movies" VALUES (02, 15);
        INSERT INTO "Roles_Movies" VALUES (01, 16);
        INSERT INTO "Roles_Movies" VALUES (02, 17);
        INSERT INTO "Roles_Movies" VALUES (01, 18);
        INSERT INTO "Roles_Movies" VALUES (02, 19);
        INSERT INTO "Roles_Movies" VALUES (01, 20);
        INSERT INTO "Roles_Movies" VALUES (02, 21);
        INSERT INTO "Roles_Movies" VALUES (01, 22);
        INSERT INTO "Roles_Movies" VALUES (02, 23);
        INSERT INTO "Roles_Movies" VALUES (01, 24);
        INSERT INTO "Roles_Movies" VALUES (02, 25);
        INSERT INTO "Roles_Movies" VALUES (01, 26);
        INSERT INTO "Roles_Movies" VALUES (02, 27);
        INSERT INTO "Roles_Movies" VALUES (01, 28);
        INSERT INTO "Roles_Movies" VALUES (02, 29);
        INSERT INTO "Roles_Movies" VALUES (01, 30);
        INSERT INTO "Roles_Movies" VALUES (02, 31);
        INSERT INTO "Roles_Movies" VALUES (01, 32);
        INSERT INTO "Roles_Movies" VALUES (02, 33);
        INSERT INTO "Roles_Movies" VALUES (01, 34);
        INSERT INTO "Roles_Movies" VALUES (01, 35);

        INSERT INTO "Role_Participants" VALUES (01, 01);
        INSERT INTO "Role_Participants" VALUES (02, 02);
        INSERT INTO "Role_Participants" VALUES (01, 03);
        INSERT INTO "Role_Participants" VALUES (02, 04);
        INSERT INTO "Role_Participants" VALUES (01, 05);
        INSERT INTO "Role_Participants" VALUES (02, 06);
        INSERT INTO "Role_Participants" VALUES (01, 07);
        INSERT INTO "Role_Participants" VALUES (02, 08);
        INSERT INTO "Role_Participants" VALUES (01, 09);
        INSERT INTO "Role_Participants" VALUES (02, 10);
        INSERT INTO "Role_Participants" VALUES (01, 11);
        INSERT INTO "Role_Participants" VALUES (02, 12);
        INSERT INTO "Role_Participants" VALUES (01, 13);
        INSERT INTO "Role_Participants" VALUES (02, 14);
        INSERT INTO "Role_Participants" VALUES (01, 15);
        INSERT INTO "Role_Participants" VALUES (02, 16);
        INSERT INTO "Role_Participants" VALUES (01, 17);
        INSERT INTO "Role_Participants" VALUES (02, 18);
        INSERT INTO "Role_Participants" VALUES (01, 19);
        INSERT INTO "Role_Participants" VALUES (02, 20);
        INSERT INTO "Role_Participants" VALUES (01, 21);
        INSERT INTO "Role_Participants" VALUES (02, 22);
        INSERT INTO "Role_Participants" VALUES (01, 23);
        INSERT INTO "Role_Participants" VALUES (02, 24);
        INSERT INTO "Role_Participants" VALUES (01, 25);
        INSERT INTO "Role_Participants" VALUES (02, 26);
        INSERT INTO "Role_Participants" VALUES (01, 27);
        INSERT INTO "Role_Participants" VALUES (02, 28);
        INSERT INTO "Role_Participants" VALUES (02, 29);
        INSERT INTO "Role_Participants" VALUES (02, 30);
        INSERT INTO "Role_Participants" VALUES (01, 31);
        INSERT INTO "Role_Participants" VALUES (02, 32);
        INSERT INTO "Role_Participants" VALUES (02, 33);
        INSERT INTO "Role_Participants" VALUES (02, 34);
        
        

        


        
          
        
    



        



